version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:

  build:

    docker:
      - image: circleci/node:9.9

    steps:
      - checkout

      - restore_cache:
          name: Restore cacher
          key: npm-cache-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependecies
          command: npm install

      - save_cache:
          name: Save cache
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - ../

      - run:
          name: Run tests
          command: npm test -- --coverage
      
      - codecov/upload:
          file: coverage/coverage-final.json