version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout
      - run:
        name: Install dependecies
        command: npm install
      - run:
        name: Run tests
        command: npm test